### ISSUE TITLE
Adding on the Powered By Faust page ?

### ISSUE THREAD

**Issue by sletz** [t2techno/Faug#1]
Great work ! Do you consider it advanced enough to be added on [Powered By Faust page](https://faust.grame.fr/community/made-with-faust/) ?

**Comment by t2techno** [comment]
Thanks Stéphane, I would love for Faug to be included on the Powered by Faust page!

While it is very much in active development, the one thing I want to do before adding it somewhere so public is another round of polish on the UI. Random parts are still misaligned, which doesn't bother me while developing but does prevent a good screenshot.

I'll move that piece up the priority list and comment back here when I'm ready!

**Comment by t2techno** [comment]
Hey @sletz, the project is definitely still in-progress, but I think it's at a good enough place to be added to the Powered By Faust Page.

**Comment by sletz** [comment]
Done https://faust.grame.fr/community/made-with-faust/#faug thanks !
